xilpm_v2_4: XilPM APIs
XilPM APIs
Modules
Pmstatmacro
Data Structures
struct XPm_Ntfier
XPm_Notifier - Notifier structure registered with a callback by app.
struct XPm_NdStatus
XPm_NodeStatus - struct containing node status information.
Typedefs
typedef struct XPm_Ntfier XPm_Notifier
XPm_Notifier - Notifier structure registered with a callback by app.
typedef struct XPm_NdStatus XPm_NodeStatus
XPm_NodeStatus - struct containing node status information.
typedef struct XPmClkModel XPmClockModel
Clock model.
Enumerations
enum XPmApiId
APIs for Miscellaneous functions, suspending of PUs, managing PM slaves and Direct control.
enum XPmApiCbId
PM API Callback Id Enum.
enum XPmNodeId
PM Node ID Enum.
enum XPmRequestAck
PM Acknowledge Request Types.
enum XPmAbortReason
PM Abort Reasons Enum.
enum XPmSuspendReason
PM Suspend Reasons Enum.
enum XPmRamState
PM RAM States Enum.
enum XPmOpCharType
PM Operating Characteristic types Enum.
enum XPmBootStatus
Boot Status Enum.
enum XPmResetAction
PM Reset Action types.
enum XPmReset
PM Reset Line IDs.
enum XPmNotifyEvent
PM Notify Events Enum.
enum XPmClock
PM Clock IDs.
Functions
XStatus XPm_InitXilpm (XIpiPsu *IpiInst)
Initialize xilpm library.
enum XPmBootStatus XPm_GetBootStatus (void)
This Function returns information about the boot reason.
void XPm_SuspendFinalize (void)
This Function waits for PMU to finish all previous API requests sent by the PU and performs client specific actions to finish suspend procedure (e.g.
XStatus XPm_SelfSuspend (const enum XPmNodeId nid, const u32 latency, const u8 state, const u64 address)
This function is used by a CPU to declare that it is about to suspend itself.
XStatus XPm_SetConfiguration (const u32 address)
This function is called to configure the power management framework.
XStatus XPm_InitFinalize (void)
This function is called to notify the power management controller about the completed power management initialization.
XStatus XPm_RequestSuspend (const enum XPmNodeId target, const enum XPmRequestAck ack, const u32 latency, const u8 state)
This function is used by a PU to request suspend of another PU.
XStatus XPm_RequestWakeUp (const enum XPmNodeId target, const bool setAddress, const u64 address, const enum XPmRequestAck ack)
This function can be used to request power up of a CPU node within the same PU, or to power up another PU.
XStatus XPm_ForcePowerDown (const enum XPmNodeId target, const enum XPmRequestAck ack)
One PU can request a forced poweroff of another PU or its power island or power domain.
XStatus XPm_AbortSuspend (const enum XPmAbortReason reason)
This function is called by a CPU after a XPm_SelfSuspend call to notify the power management controller that CPU has aborted suspend or in response to an init suspend request when the PU refuses to suspend.
XStatus XPm_SetWakeUpSource (const enum XPmNodeId target, const enum XPmNodeId wkup_node, const u8 enable)
This function is called by a PU to add or remove a wake-up source prior to going to suspend.
XStatus XPm_SystemShutdown (u32 type, u32 subtype)
This function can be used by a privileged PU to shut down or restart the complete device.
XStatus XPm_RequestNode (const enum XPmNodeId node, const u32 capabilities, const u32 qos, const enum XPmRequestAck ack)
Used to request the usage of a PM-slave.
XStatus XPm_SetRequirement (const enum XPmNodeId nid, const u32 capabilities, const u32 qos, const enum XPmRequestAck ack)
This function is used by a PU to announce a change in requirements for a specific slave node which is currently in use.
XStatus XPm_ReleaseNode (const enum XPmNodeId node)
This function is used by a PU to release the usage of a PM slave.
XStatus XPm_SetMaxLatency (const enum XPmNodeId node, const u32 latency)
This function is used by a PU to announce a change in the maximum wake-up latency requirements for a specific slave node currently used by that PU.
void XPm_InitSuspendCb (const enum XPmSuspendReason reason, const u32 latency, const u32 state, const u32 timeout)
Callback function to be implemented in each PU, allowing the power management controller to request that the PU suspend itself.
void XPm_AcknowledgeCb (const enum XPmNodeId node, const XStatus status, const u32 oppoint)
This function is called by the power management controller in response to any request where an acknowledge callback was requested, i.e.
void XPm_NotifyCb (const enum XPmNodeId node, const enum XPmNotifyEvent event, const u32 oppoint)
This function is called by the power management controller if an event the PU was registered for has occurred.
XStatus XPm_GetApiVersion (u32 *version)
This function is used to request the version number of the API running on the power management controller.
XStatus XPm_GetNodeStatus (const enum XPmNodeId node, XPm_NodeStatus *const nodestatus)
This function is used to obtain information about the current state of a component.
XStatus XPm_GetOpCharacteristic (const enum XPmNodeId node, const enum XPmOpCharType type, u32 *const result)
Call this function to request the power management controller to return information about an operating characteristic of a component.
XStatus XPm_ResetAssert (const enum XPmReset reset, const enum XPmResetAction resetaction)
This function is used to assert or release reset for a particular reset line.
XStatus XPm_ResetGetStatus (const enum XPmReset reset, u32 *status)
Call this function to get the current status of the selected reset line.
XStatus XPm_RegisterNotifier (XPm_Notifier *const notifier)
A PU can call this function to request that the power management controller call its notify callback whenever a qualifying event occurs.
XStatus XPm_UnregisterNotifier (XPm_Notifier *const notifier)
A PU calls this function to unregister for the previously requested notifications.
XStatus XPm_MmioWrite (const u32 address, const u32 mask, const u32 value)
Call this function to write a value directly into a register that isn't accessible directly, such as registers in the clock control unit.
XStatus XPm_MmioRead (const u32 address, u32 *const value)
Call this function to read a value from a register that isn't accessible directly.
XStatus XPm_ClockEnable (const enum XPmClock clock)
Call this function to enable (activate) a clock.
XStatus XPm_ClockDisable (const enum XPmClock clock)
Call this function to disable (gate) a clock.
XStatus XPm_ClockGetStatus (const enum XPmClock clock, u32 *const status)
Call this function to get status of a clock gate state.
XStatus XPm_ClockSetDivider (const enum XPmClock clock, const u32 divider)
Call this function to set divider for a clock.
XStatus XPm_ClockGetDivider (const enum XPmClock clock, u32 *const divider)
Call this function to get divider of a clock.
XStatus XPm_ClockSetParent (const enum XPmClock clock, const enum XPmClock parent)
Call this function to set parent for a clock.
XStatus XPm_ClockGetParent (const enum XPmClock clock, enum XPmClock *const parent)
Call this function to get parent of a clock.
XStatus XPm_ClockSetRate (const enum XPmClock clock, const u32 rate)
Call this function to set rate of a clock.
XStatus XPm_ClockGetRate (const enum XPmClock clock, u32 *const rate)
Call this function to get rate of a clock.
XStatus XPm_PllSetParameter (const enum XPmNodeId node, const enum XPmPllParam parameter, const u32 value)
Call this function to set a PLL parameter.
XStatus XPm_PllGetParameter (const enum XPmNodeId node, const enum XPmPllParam parameter, u32 *const value)
Call this function to get a PLL parameter.
XStatus XPm_PllSetMode (const enum XPmNodeId node, const enum XPmPllMode mode)
Call this function to set a PLL mode.
XStatus XPm_PllGetMode (const enum XPmNodeId node, enum XPmPllMode *const mode)
Call this function to get a PLL mode.
XStatus XPm_PinCtrlRequest (const u32 pin)
Call this function to request a pin control.
XStatus XPm_PinCtrlRelease (const u32 pin)
Call this function to release a pin control.
XStatus XPm_PinCtrlSetFunction (const u32 pin, const enum XPmPinFn fn)
Call this function to set a pin function.
XStatus XPm_PinCtrlGetFunction (const u32 pin, enum XPmPinFn *const fn)
Call this function to get currently configured pin function.
XStatus XPm_PinCtrlSetParameter (const u32 pin, const enum XPmPinParam param, const u32 value)
Call this function to set a pin parameter.
XStatus XPm_PinCtrlGetParameter (const u32 pin, const enum XPmPinParam param, u32 *const value)
Call this function to get currently configured value of pin parameter.
XStatus XPm_NotifierAdd (XPm_Notifier *const notifier)
Add notifier into the list.
XStatus XPm_NotifierRemove (XPm_Notifier *const notifier)
Remove notifier from the list.
void XPm_NotifierProcessEvent (const enum XPmNodeId node, const enum XPmNotifyEvent event, const u32 oppoint)
Call to process notification event.
XStatus XPm_GetClockParentBySelect (const enum XPmClock clockId, const u32 select, enum XPmClock *const parentId)
Get parent clock ID for a given clock ID and mux select value.
XStatus XPm_GetSelectByClockParent (const enum XPmClock clockId, const enum XPmClock parentId, u32 *const select)
Get mux select value for given clock and clock parent IDs.
u8 XPm_GetClockDivType (const enum XPmClock clock)
Get number of divider that a given clock has.
u8 XPm_MapDivider (const enum XPmClock clock, const u32 div, u32 *const div0, u32 *const div1)
Map effective divider value for given clock on DIV0 and DIV1 dividers.
Payload Packets
Assigning of argument values into array elements.
pause and pm_dbg are used for debugging and should be removed in final version.
#define PACK_PAYLOAD(pl, arg0, arg1, arg2, arg3, arg4, arg5, rsvd)
#define PACK_PAYLOAD0(pl, api_id) PACK_PAYLOAD(pl, (api_id), 0U, 0U, 0U, 0U, 0U, 0U)
#define PACK_PAYLOAD1(pl, api_id, arg1) PACK_PAYLOAD(pl, (api_id), (arg1), 0U, 0U, 0U, 0U, 0U)
#define PACK_PAYLOAD2(pl, api_id, arg1, arg2) PACK_PAYLOAD(pl, (api_id), (arg1), (arg2), 0U, 0U, 0U, 0U)
#define PACK_PAYLOAD3(pl, api_id, arg1, arg2, arg3) PACK_PAYLOAD(pl, (api_id), (arg1), (arg2), (arg3), 0U, 0U, 0U)
#define PACK_PAYLOAD4(pl, api_id, arg1, arg2, arg3, arg4) PACK_PAYLOAD(pl, (api_id), (arg1), (arg2), (arg3), (arg4), 0U, 0U)
#define PACK_PAYLOAD5(pl, api_id, arg1, arg2, arg3, arg4, arg5) PACK_PAYLOAD(pl, (api_id), (arg1), (arg2), (arg3), (arg4), (arg5), 0U)
PM Version Number macros
#define PM_VERSION_MAJOR 1
#define PM_VERSION_MINOR 1
#define PM_VERSION ((PM_VERSION_MAJOR << 16) | PM_VERSION_MINOR)
Capabilities for RAM
#define PM_CAP_ACCESS 0x1U
#define PM_CAP_CONTEXT 0x2U
#define PM_CAP_WAKEUP 0x4U
Node default states macros
#define NODE_STATE_OFF 0
#define NODE_STATE_ON 1
Processor's states macros
#define PROC_STATE_FORCEDOFF 0
#define PROC_STATE_ACTIVE 1
#define PROC_STATE_SLEEP 2
#define PROC_STATE_SUSPENDING 3
Maximum Latency/QOS macros
#define MAX_LATENCY (~0U)
#define MAX_QOS 100U
System shutdown/Restart macros
#define PMF_SHUTDOWN_TYPE_SHUTDOWN 0U
#define PMF_SHUTDOWN_TYPE_RESET 1U
#define PMF_SHUTDOWN_SUBTYPE_SUBSYSTEM 0U
#define PMF_SHUTDOWN_SUBTYPE_PS_ONLY 1U
#define PMF_SHUTDOWN_SUBTYPE_SYSTEM 2U
PM API Min and Max macros
#define PM_API_MIN PM_GET_API_VERSION
Typedef Documentation
typedef struct XPm_NdStatus XPm_NodeStatus
XPm_NodeStatus - struct containing node status information.
typedef struct XPm_Ntfier XPm_Notifier
XPm_Notifier - Notifier structure registered with a callback by app.
typedef struct XPmClkModel XPmClockModel
Clock model.
Enumeration Type Documentation
enum XPmAbortReason
PM Abort Reasons Enum.
enum XPmApiCbId
PM API Callback Id Enum.
enum XPmApiId
APIs for Miscellaneous functions, suspending of PUs, managing PM slaves and Direct control.
enum XPmBootStatus
Boot Status Enum.
enum XPmClock
PM Clock IDs.
enum XPmNodeId
PM Node ID Enum.
enum XPmNotifyEvent
PM Notify Events Enum.
enum XPmOpCharType
PM Operating Characteristic types Enum.
enum XPmRamState
PM RAM States Enum.
enum XPmRequestAck
PM Acknowledge Request Types.
enum XPmReset
PM Reset Line IDs.
enum XPmResetAction
PM Reset Action types.
enum XPmSuspendReason
PM Suspend Reasons Enum.
Function Documentation
XStatus XPm_AbortSuspend (const enum XPmAbortReason reason)
This function is called by a CPU after a XPm_SelfSuspend call to notify the power management controller that CPU has aborted suspend or in response to an init suspend request when the PU refuses to suspend.
Parameters
reason Reason code why the suspend can not be performed or completed
ABORT_REASON_WKUP_EVENT : local wakeup-event received
ABORT_REASON_PU_BUSY : PU is busy
ABORT_REASON_NO_PWRDN : no external powerdown supported
ABORT_REASON_UNKNOWN : unknown error during suspend procedure
Returns
XST_SUCCESS if successful else XST_FAILURE or an error code or a reason code
Note
Calling PU expects the PMU to abort the initiated suspend procedure. This is a non-blocking call without any acknowledge.
References XPm_Master::node_id.
void XPm_AcknowledgeCb (const enum XPmNodeId node, const XStatus status, const u32 oppoint)
This function is called by the power management controller in response to any request where an acknowledge callback was requested, i.e.
where the 'ack' argument passed by the PU was REQUEST_ACK_NON_BLOCKING.
Parameters
node ID of the component or sub-system in question.
status Status of the operation:
OK: the operation completed successfully
ERR: the requested operation failed
oppoint Operating point of the node in question
Returns
None
Note
None
XStatus XPm_ClockDisable (const enum XPmClock clock)
Call this function to disable (gate) a clock.
Parameters
clock Identifier of the target clock to be disabled
Returns
Status of performing the operation as returned by the PMU-FW
Note
If the access isn't permitted this function returns an error code.
XStatus XPm_ClockEnable (const enum XPmClock clock)
Call this function to enable (activate) a clock.
Parameters
clock Identifier of the target clock to be enabled
Returns
Status of performing the operation as returned by the PMU-FW
Note
If the access isn't permitted this function returns an error code.
XStatus XPm_ClockGetDivider (const enum XPmClock clock, u32 *const divider)
Call this function to get divider of a clock.
Parameters
clock Identifier of the target clock
divider Location to store the divider value
Returns
XST_INVALID_PARAM or status of performing the operation as returned by the PMU-FW
References XPm_GetClockDivType().
XStatus XPm_ClockGetParent (const enum XPmClock clock, enum XPmClock *const parent)
Call this function to get parent of a clock.
Parameters
clock Identifier of the target clock
parent Location to store clock parent ID
Returns
XST_INVALID_PARAM or status of performing the operation as returned by the PMU-FW.
References XPm_GetClockParentBySelect().
XStatus XPm_ClockGetRate (const enum XPmClock clock, u32 *const rate)
Call this function to get rate of a clock.
Parameters
clock Identifier of the target clock
rate Location where the rate should be stored
Returns
Status of performing the operation as returned by the PMU-FW
XStatus XPm_ClockGetStatus (const enum XPmClock clock, u32 *const status)
Call this function to get status of a clock gate state.
Parameters
clock Identifier of the target clock
status Location to store clock gate state (1=enabled, 0=disabled)
Returns
Status of performing the operation as returned by the PMU-FW
XStatus XPm_ClockSetDivider (const enum XPmClock clock, const u32 divider)
Call this function to set divider for a clock.
Parameters
clock Identifier of the target clock
divider Divider value to be set
Returns
XST_INVALID_PARAM or status of performing the operation as returned by the PMU-FW
Note
If the access isn't permitted this function returns an error code.
References XPm_GetClockDivType(), and XPm_MapDivider().
XStatus XPm_ClockSetParent (const enum XPmClock clock, const enum XPmClock parent)
Call this function to set parent for a clock.
Parameters
clock Identifier of the target clock
parent Identifier of the target parent clock
Returns
XST_INVALID_PARAM or status of performing the operation as returned by the PMU-FW.
Note
If the access isn't permitted this function returns an error code.
References XPm_GetSelectByClockParent().
XStatus XPm_ClockSetRate (const enum XPmClock clock, const u32 rate)
Call this function to set rate of a clock.
Parameters
clock Identifier of the target clock
rate Clock frequency (rate) to be set
Returns
Status of performing the operation as returned by the PMU-FW
Note
If the action isn't permitted this function returns an error code.
XStatus XPm_ForcePowerDown (const enum XPmNodeId target, const enum XPmRequestAck ack)
One PU can request a forced poweroff of another PU or its power island or power domain.
This can be used for killing an unresponsive PU, in which case all resources of that PU will be automatically released.
Parameters
target Node ID of the PU node or power island/domain to be powered down.
ack Requested acknowledge type
Returns
XST_SUCCESS if successful else XST_FAILURE or an error code or a reason code
Note
Force power down may not be requested by a PU for itself.
XStatus XPm_GetApiVersion (u32 * version)
This function is used to request the version number of the API running on the power management controller.
Parameters
version Returns the API 32-bit version number. Returns 0 if no PM firmware present.
Returns
XST_SUCCESS if successful else XST_FAILURE or an error code or a reason code
Note
None
enum XPmBootStatus XPm_GetBootStatus (void)
This Function returns information about the boot reason.
If the boot is not a system startup but a resume, power down request bitfield for this processor will be cleared.
Returns
Returns processor boot status
PM_RESUME : If the boot reason is because of system resume.
PM_INITIAL_BOOT : If this boot is the initial system startup.
Note
None
References XPm_Master::pwrdn_mask.
u8 XPm_GetClockDivType (const enum XPmClock clock)
Get number of divider that a given clock has.
Parameters
clock ID of the target clock
Returns
Encoded clock divider types. If the clock ID is invalid zero is returned.
Note
None
Referenced by XPm_ClockGetDivider(), and XPm_ClockSetDivider().
XStatus XPm_GetClockParentBySelect (const enum XPmClock clockId, const u32 select, enum XPmClock *const parentId)
Get parent clock ID for a given clock ID and mux select value.
Parameters
clockId ID of the target clock
select Mux select value
parentId Location to store parent clock ID
Returns
Returns XST_SUCCESS if parent clock ID is found, XST_INVALID_PARAM otherwise.
Note
None
Referenced by XPm_ClockGetParent().
XStatus XPm_GetNodeStatus (const enum XPmNodeId node, XPm_NodeStatus *const nodestatus)
This function is used to obtain information about the current state of a component.
The caller must pass a pointer to an XPm_NodeStatus structure, which must be pre-allocated by the caller.
Parameters
node ID of the component or sub-system in question.
nodestatus Used to return the complete status of the node.
status - The current power state of the requested node.
For CPU nodes:
0 : if CPU is powered down,
1 : if CPU is active (powered up),
2 : if CPU is suspending (powered up)
For power islands and power domains:
0 : if island is powered down,
1 : if island is powered up
For PM slaves:
0 : if slave is powered down,
1 : if slave is powered up,
2 : if slave is in retention
requirement - Slave nodes only: Returns current requirements the requesting PU has requested of the node.
usage - Slave nodes only: Returns current usage status of the node:
0 : node is not used by any PU,
1 : node is used by caller exclusively,
2 : node is used by other PU(s) only,
3 : node is used by caller and by other PU(s)
Returns
XST_SUCCESS if successful else XST_FAILURE or an error code or a reason code
Note
None
References XPm_NdStatus::requirements, XPm_NdStatus::status, and XPm_NdStatus::usage.
XStatus XPm_GetOpCharacteristic (const enum XPmNodeId node, const enum XPmOpCharType type, u32 *const result)
Call this function to request the power management controller to return information about an operating characteristic of a component.
Parameters
node ID of the component or sub-system in question.
type Type of operating characteristic requested:
power (current power consumption),
latency (current latency in us to return to active state),
temperature (current temperature),
result Used to return the requested operating characteristic.
Returns
XST_SUCCESS if successful else XST_FAILURE or an error code or a reason code
Note
None
XStatus XPm_GetSelectByClockParent (const enum XPmClock clockId, const enum XPmClock parentId, u32 *const select)
Get mux select value for given clock and clock parent IDs.
Parameters
clockId ID of the target clock
parentId ID of the parent clock
select Location to store mux select value
Returns
Returns XST_SUCCESS if select value is found, XST_INVALID_PARAM otherwise.
Note
None
Referenced by XPm_ClockSetParent().
XStatus XPm_InitFinalize (void)
This function is called to notify the power management controller about the completed power management initialization.
Returns
XST_SUCCESS if successful, otherwise an error code
Note
It is assumed that all used nodes are requested when this call is made. The power management controller may power down the nodes which are not requested after this call is processed.
void XPm_InitSuspendCb (const enum XPmSuspendReason reason, const u32 latency, const u32 state, const u32 timeout)
Callback function to be implemented in each PU, allowing the power management controller to request that the PU suspend itself.
Parameters
reason Suspend reason:
SUSPEND_REASON_PU_REQ : Request by another PU
SUSPEND_REASON_ALERT : Unrecoverable SysMon alert
SUSPEND_REASON_SHUTDOWN : System shutdown
SUSPEND_REASON_RESTART : System restart
latency Maximum wake-up latency in us(micro secs). This information can be used by the PU to decide what level of context saving may be required.
state Targeted sleep/suspend state.
timeout Timeout in ms, specifying how much time a PU has to initiate its suspend procedure before it's being considered unresponsive.
Returns
None
Note
If the PU fails to act on this request the power management controller or the requesting PU may choose to employ the forceful power down option.
XStatus XPm_InitXilpm (XIpiPsu * IpiInst)
Initialize xilpm library.
Parameters
IpiInst Pointer to IPI driver instance
Returns
XST_SUCCESS if successful else XST_FAILURE or an error code or a reason code
Note
None
References XPm_Master::ipi.
u8 XPm_MapDivider (const enum XPmClock clock, const u32 div, u32 *const div0, u32 *const div1)
Map effective divider value for given clock on DIV0 and DIV1 dividers.
Parameters
clock ID of the target clock
div Effective divider value
div0 Location to store mapped DIV0 value
div1 Location to store mapped DIV1 value
Returns
Encoded mask of mapped dividers
Note
The effective divider value may not be mappable on 2x 6-bit wide dividers. This is the case if a given divider value is higher than 6-bit divider (requires 2xdividers), but its a prime number (cannot be divided to get 2x divider values).
Referenced by XPm_ClockSetDivider().
XStatus XPm_MmioRead (const u32 address, u32 *const value)
Call this function to read a value from a register that isn't accessible directly.
The permitted addresses are subject to restrictions as defined in the PCW configuration.
Parameters
address Physical 32-bit address of memory mapped register to read from.
value Returns the 32-bit value read from the register
Returns
XST_SUCCESS if successful else XST_FAILURE or an error code or a reason code
Note
If the access isn't permitted this function returns an error code.
XStatus XPm_MmioWrite (const u32 address, const u32 mask, const u32 value)
Call this function to write a value directly into a register that isn't accessible directly, such as registers in the clock control unit.
This call is bypassing the power management logic. The permitted addresses are subject to restrictions as defined in the PCW configuration.
Parameters
address Physical 32-bit address of memory mapped register to write to.
mask 32-bit value used to limit write to specific bits in the register.
value Value to write to the register bits specified by the mask.
Returns
XST_SUCCESS if successful else XST_FAILURE or an error code or a reason code
Note
If the access isn't permitted this function returns an error code.
XStatus XPm_NotifierAdd (XPm_Notifier *const notifier)
Add notifier into the list.
Parameters
notifier Pointer to notifier object which needs to be added in the list
Returns
Returns XST_SUCCESS if notifier is added / XST_INVALID_PARAM if given notifier argument is NULL
Note
None
References XPm_Ntfier::next, and XPm_Ntfier::received.
Referenced by XPm_RegisterNotifier().
void XPm_NotifierProcessEvent (const enum XPmNodeId node, const enum XPmNotifyEvent event, const u32 oppoint)
Call to process notification event.
Parameters
node Node which is the subject of notification
event Event which is the subject of notification
oppoint Operating point of the node in question
Returns
None
Note
None
References XPm_Ntfier::callback, XPm_Ntfier::event, XPm_Ntfier::next, XPm_Ntfier::node, XPm_Ntfier::oppoint, and XPm_Ntfier::received.
Referenced by XPm_NotifyCb().
XStatus XPm_NotifierRemove (XPm_Notifier *const notifier)
Remove notifier from the list.
Parameters
notifier Pointer to notifier object to be removed from list
Returns
Returns XST_SUCCESS if notifier is removed / XST_INVALID_PARAM if given notifier pointer is NULL / XST_FAILURE if notifier is not found
Note
None
References XPm_Ntfier::next.
Referenced by XPm_UnregisterNotifier().
void XPm_NotifyCb (const enum XPmNodeId node, const enum XPmNotifyEvent event, const u32 oppoint)
This function is called by the power management controller if an event the PU was registered for has occurred.
It will populate the notifier data structure passed when calling XPm_RegisterNotifier.
Parameters
node ID of the node the event notification is related to.
event ID of the event
oppoint Current operating state of the node.
Returns
None
Note
None
References XPm_NotifierProcessEvent().
XStatus XPm_PinCtrlGetFunction (const u32 pin, enum XPmPinFn *const fn)
Call this function to get currently configured pin function.
Parameters
pin PLL node identifier
fn Location to store the pin function
Returns
Status of performing the operation as returned by the PMU-FW
XStatus XPm_PinCtrlGetParameter (const u32 pin, const enum XPmPinParam param, u32 *const value)
Call this function to get currently configured value of pin parameter.
Parameters
pin Pin identifier
param Pin parameter identifier
value Location to store value of the pin parameter
Returns
Status of performing the operation as returned by the PMU-FW
XStatus XPm_PinCtrlRelease (const u32 pin)
Call this function to release a pin control.
Parameters
pin PIN identifier (index from range 0-77)
Returns
Status of performing the operation as returned by the PMU-FW
XStatus XPm_PinCtrlRequest (const u32 pin)
Call this function to request a pin control.
Parameters
pin PIN identifier (index from range 0-77)
Returns
Status of performing the operation as returned by the PMU-FW
XStatus XPm_PinCtrlSetFunction (const u32 pin, const enum XPmPinFn fn)
Call this function to set a pin function.
Parameters
pin Pin identifier
fn Pin function to be set
Returns
Status of performing the operation as returned by the PMU-FW
Note
If the access isn't permitted this function returns an error code.
XStatus XPm_PinCtrlSetParameter (const u32 pin, const enum XPmPinParam param, const u32 value)
Call this function to set a pin parameter.
Parameters
pin Pin identifier
param Pin parameter identifier
value Value of the pin parameter to set
Returns
Status of performing the operation as returned by the PMU-FW
Note
If the access isn't permitted this function returns an error code.
XStatus XPm_PllGetMode (const enum XPmNodeId node, enum XPmPllMode *const mode)
Call this function to get a PLL mode.
Parameters
node PLL node identifier
mode Location to store the PLL mode
Returns
Status of performing the operation as returned by the PMU-FW
XStatus XPm_PllGetParameter (const enum XPmNodeId node, const enum XPmPllParam parameter, u32 *const value)
Call this function to get a PLL parameter.
Parameters
node PLL node identifier
parameter PLL parameter identifier
value Location to store value of the PLL parameter
Returns
Status of performing the operation as returned by the PMU-FW
XStatus XPm_PllSetMode (const enum XPmNodeId node, const enum XPmPllMode mode)
Call this function to set a PLL mode.
Parameters
node PLL node identifier
mode PLL mode to be set
Returns
Status of performing the operation as returned by the PMU-FW
Note
If the access isn't permitted this function returns an error code.
XStatus XPm_PllSetParameter (const enum XPmNodeId node, const enum XPmPllParam parameter, const u32 value)
Call this function to set a PLL parameter.
Parameters
node PLL node identifier
parameter PLL parameter identifier
value Value of the PLL parameter
Returns
Status of performing the operation as returned by the PMU-FW
Note
If the access isn't permitted this function returns an error code.
XStatus XPm_RegisterNotifier (XPm_Notifier *const notifier)
A PU can call this function to request that the power management controller call its notify callback whenever a qualifying event occurs.
One can request to be notified for a specific or any event related to a specific node.
Parameters
notifier Pointer to the notifier object to be associated with the requested notification. The notifier object contains the following data related to the notification:
nodeID : ID of the node to be notified about,
eventID : ID of the event in question, '-1' denotes all events (- EVENT_STATE_CHANGE, EVENT_ZERO_USERS),
wake : true: wake up on event, false: do not wake up (only notify if awake), no buffering/queueing
callback : Pointer to the custom callback function to be called when the notification is available. The callback executes from interrupt context, so the user must take special care when implementing the callback. Callback is optional, may be set to NULL.
received : Variable indicating how many times the notification has been received since the notifier is registered.
Returns
XST_SUCCESS if successful else XST_FAILURE or an error code or a reason code
Note
The caller shall initialize the notifier object before invoking the XPm_RegisteredNotifier function. While notifier is registered, the notifier object shall not be modified by the caller.
References XPm_Ntfier::event, XPm_Ntfier::flags, XPm_Ntfier::node, and XPm_NotifierAdd().
XStatus XPm_ReleaseNode (const enum XPmNodeId node)
This function is used by a PU to release the usage of a PM slave.
This will tell the power management controller that the node is no longer needed by that PU, potentially allowing the node to be placed into an inactive state.
Parameters
node Node ID of the PM slave.
Returns
XST_SUCCESS if successful else XST_FAILURE or an error code or a reason code
Note
None
XStatus XPm_RequestNode (const enum XPmNodeId node, const u32 capabilities, const u32 qos, const enum XPmRequestAck ack)
Used to request the usage of a PM-slave.
Using this API call a PU requests access to a slave device and asserts its requirements on that device. Provided the PU is sufficiently privileged, the PMU will enable access to the memory mapped region containing the control registers of that device. For devices that can only be serving a single PU, any other privileged PU will now be blocked from accessing this device until the node is released.
Parameters
node Node ID of the PM slave requested
capabilities Slave-specific capabilities required, can be combined
PM_CAP_ACCESS : full access / functionality
PM_CAP_CONTEXT : preserve context
PM_CAP_WAKEUP : emit wake interrupts
qos Quality of Service (0-100) required
ack Requested acknowledge type
Returns
XST_SUCCESS if successful else XST_FAILURE or an error code or a reason code
Note
None
XStatus XPm_RequestSuspend (const enum XPmNodeId target, const enum XPmRequestAck ack, const u32 latency, const u8 state)
This function is used by a PU to request suspend of another PU.
This call triggers the power management controller to notify the PU identified by 'nodeID' that a suspend has been requested. This will allow said PU to gracefully suspend itself by calling XPm_SelfSuspend for each of its CPU nodes, or else call XPm_AbortSuspend with its PU node as argument and specify the reason.
Parameters
target Node ID of the PU node to be suspended
ack Requested acknowledge type
latency Maximum wake-up latency requirement in us(micro sec)
state Instead of specifying a maximum latency, a PU can also explicitly request a certain power state.
Returns
XST_SUCCESS if successful else XST_FAILURE or an error code or a reason code
Note
If 'ack' is set to PM_ACK_NON_BLOCKING, the requesting PU will be notified upon completion of suspend or if an error occurred, such as an abort. REQUEST_ACK_BLOCKING is not supported for this command.
XStatus XPm_RequestWakeUp (const enum XPmNodeId target, const bool setAddress, const u64 address, const enum XPmRequestAck ack)
This function can be used to request power up of a CPU node within the same PU, or to power up another PU.
Parameters
target Node ID of the CPU or PU to be powered/woken up.
setAddress Specifies whether the start address argument is being passed.
0 : do not set start address
1 : set start address
address Address from which to resume when woken up. Will only be used if set_address is 1.
ack Requested acknowledge type
Returns
XST_SUCCESS if successful else XST_FAILURE or an error code or a reason code
Note
If acknowledge is requested, the calling PU will be notified by the power management controller once the wake-up is completed.
XStatus XPm_ResetAssert (const enum XPmReset reset, const enum XPmResetAction resetaction)
This function is used to assert or release reset for a particular reset line.
Alternatively a reset pulse can be requested as well.
Parameters
reset ID of the reset line
assert Identifies action:
PM_RESET_ACTION_RELEASE : release reset,
PM_RESET_ACTION_ASSERT : assert reset,
PM_RESET_ACTION_PULSE : pulse reset,
Returns
XST_SUCCESS if successful else XST_FAILURE or an error code or a reason code
Note
None
XStatus XPm_ResetGetStatus (const enum XPmReset reset, u32 * status)
Call this function to get the current status of the selected reset line.
Parameters
reset Reset line
status Status of specified reset (true - asserted, false - released)
Returns
Returns 1/XST_FAILURE for 'asserted' or 0/XST_SUCCESS for 'released'.
Note
None
XStatus XPm_SelfSuspend (const enum XPmNodeId nid, const u32 latency, const u8 state, const u64 address)
This function is used by a CPU to declare that it is about to suspend itself.
After the PMU processes this call it will wait for the requesting CPU to complete the suspend procedure and become ready to be put into a sleep state.
Parameters
nid Node ID of the CPU node to be suspended.
latency Maximum wake-up latency requirement in us(microsecs)
state Instead of specifying a maximum latency, a CPU can also explicitly request a certain power state.
address Address from which to resume when woken up.
Returns
XST_SUCCESS if successful else XST_FAILURE or an error code or a reason code
Note
This is a blocking call, it will return only once PMU has responded
XStatus XPm_SetConfiguration (const u32 address)
This function is called to configure the power management framework.
The call triggers power management controller to load the configuration object and configure itself according to the content of the object.
Parameters
address Start address of the configuration object
Returns
XST_SUCCESS if successful, otherwise an error code
Note
The provided address must be in 32-bit address space which is accessible by the PMU.
XStatus XPm_SetMaxLatency (const enum XPmNodeId node, const u32 latency)
This function is used by a PU to announce a change in the maximum wake-up latency requirements for a specific slave node currently used by that PU.
Parameters
node Node ID of the PM slave.
latency Maximum wake-up latency required.
Returns
XST_SUCCESS if successful else XST_FAILURE or an error code or a reason code
Note
Setting maximum wake-up latency can constrain the set of possible power states a resource can be put into.
XStatus XPm_SetRequirement (const enum XPmNodeId nid, const u32 capabilities, const u32 qos, const enum XPmRequestAck ack)
This function is used by a PU to announce a change in requirements for a specific slave node which is currently in use.
Parameters
nid Node ID of the PM slave.
capabilities Slave-specific capabilities required.
qos Quality of Service (0-100) required.
ack Requested acknowledge type
Returns
XST_SUCCESS if successful else XST_FAILURE or an error code or a reason code
Note
If this function is called after the last awake CPU within the PU calls SelfSuspend, the requirement change shall be performed after the CPU signals the end of suspend to the power management controller, (e.g. WFI interrupt).
XStatus XPm_SetWakeUpSource (const enum XPmNodeId target, const enum XPmNodeId wkup_node, const u8 enable)
This function is called by a PU to add or remove a wake-up source prior to going to suspend.
The list of wake sources for a PU is automatically cleared whenever the PU is woken up or when one of its CPUs aborts the suspend procedure.
Parameters
target Node ID of the target to be woken up.
wkup_node Node ID of the wakeup device.
enable Enable flag:
1 : the wakeup source is added to the list
0 : the wakeup source is removed from the list
Returns
XST_SUCCESS if successful else XST_FAILURE or an error code or a reason code
Note
Declaring a node as a wakeup source will ensure that the node will not be powered off. It also will cause the PMU to configure the GIC Proxy accordingly if the FPD is powered off.
void XPm_SuspendFinalize (void)
This Function waits for PMU to finish all previous API requests sent by the PU and performs client specific actions to finish suspend procedure (e.g.
execution of wfi instruction on A53 and R5 processors).
Note
This function should not return if the suspend procedure is successful.
References XPm_Master::ipi.
XStatus XPm_SystemShutdown (u32 type, u32 subtype)
This function can be used by a privileged PU to shut down or restart the complete device.
Parameters
restart Should the system be restarted automatically?
PM_SHUTDOWN : no restart requested, system will be powered off permanently
PM_RESTART : restart is requested, system will go through a full reset
Returns
XST_SUCCESS if successful else XST_FAILURE or an error code or a reason code
Note
In either case the PMU will call XPm_InitSuspendCb for each of the other PUs, allowing them to gracefully shut down. If a PU is asleep it will be woken up by the PMU. The PU making the XPm_SystemShutdown should perform its own suspend procedure after calling this API. It will not receive an init suspend callback.
XStatus XPm_UnregisterNotifier (XPm_Notifier *const notifier)
A PU calls this function to unregister for the previously requested notifications.
Parameters
notifier Pointer to the notifier object associated with the previously requested notification
Returns
XST_SUCCESS if successful else XST_FAILURE or an error code or a reason code
Note
None
References XPm_Ntfier::event, XPm_Ntfier::node, and XPm_NotifierRemove().