xilpdi_v1_0: xilpdi.h File Reference
xilpdi.h File Reference
Overview
This is the header file which contains definitions for the PDI.
MODIFICATION HISTORY:
Ver   Who  Date        Changes
----- ---- -------- -------------------------------------------------------
1.00  kc   12/21/2017 Initial release
Note
Data Structures
struct XilPdi_BootHdrFwRsvd
Structure to store the Boot Header PMC FW fields.
struct XilPdi_BootHdr
Structure to store the boot header table details.
struct XilPdi_ImgHdrTable
Structure to store the image header table details.
struct XilPdi_ImgHdr
Structure to store the Image header details.
struct XilPdi_PrtnHdr
Structure to store the partition header details.
struct XilPdi_MetaHdr
Structure of the image header which contains information of image header table and partition headers.
Macros
#define XIH_ATTRB_A72_EXEC_ST_SHIFT_DIFF (3U)
Below is the bit mapping of fields in the ATF Handoff parameters with that of Prtn header.
#define XILPDI_ERR_IHT_CHECKSUM (0x1U)
Errors during XILDPI processing.
Functions
u32 XilPdi_GetSBD (const XilPdi_ImgHdrTable *ImgHdrTbl)
This function will return the Secondary boot device.
XStatus XilPdi_ValidateChecksum (u32 Buffer[], u32 Len)
This function is used to validate the word checksum for the image header table and partition headers.
XStatus XilPdi_ValidatePrtnHdr (XilPdi_PrtnHdr *PrtnHdr)
This function validates the partition header.
XStatus XilPdi_ValidateImgHdrTable (XilPdi_ImgHdrTable *ImgHdrTable)
This function checks the fields of the image header table and validates them.
XStatus XilPdi_ReadBootHdr (XilPdi_MetaHdr *ImgHdrPtr)
This function reads the boot header.
XStatus XilPdi_ReadImgHdrTbl (XilPdi_MetaHdr *ImgHdrPtr)
This function Reads the image header table.
XStatus XilPdi_ReadAndVerifyImgHdr (XilPdi_MetaHdr *MetaHdrPtr)
This function reads and verifies the image header.
XStatus XilPdi_ReadAndVerifyPrtnHdr (XilPdi_MetaHdr *ImgHdrPtr)
This function reads and verifies the partition header.
XStatus XilPdi_ReadAlignedData (XilPdi_MetaHdr *MetaHdrPtr, u32 PrtnNum)
This function reads aligned data of partition.
Macro Definition Documentation
#define XIH_ATTRB_A72_EXEC_ST_SHIFT_DIFF (3U)
Below is the bit mapping of fields in the ATF Handoff parameters with that of Prtn header.
The number of bits shifted is is based on the difference between these two offsets
              ATFHandoffParams      PrtnHdr         Shift
Parameter     PrtnFlags     PrtnAttrb   difference
Exec State 0 3 3 right ENDIAN 1 18 17 right SECURE 2 0 2 left EL 3:4 1:2 2 left CPU_A72 5:6 8:10
#define XILPDI_ERR_IHT_CHECKSUM (0x1U)
Errors during XILDPI processing.
Referenced by XilPdi_ValidateImgHdrTable().
Function Documentation
u32 XilPdi_GetSBD (const XilPdi_ImgHdrTable * ImgHdrTbl)
This function will return the Secondary boot device.
Parameters
ImgHdrTbl Pointer to the Image Header table.
Returns
Secondary Boot device
References XilPdi_ImgHdrTable::Attr.
XStatus XilPdi_ReadAlignedData (XilPdi_MetaHdr * MetaHdrPtr, u32 PrtnNum)
This function reads aligned data of partition.
Every partition is aligned to 64 bytes
Parameters
MetaHdrPtr is pointer to the XilPdi_MetaHdr structure
PrtnNum is the number of partition
Returns
XST_SUCCESS on successful reading of aligned data
errors as mentioned in xilpdi.h
Note
References XilPdi_MetaHdr::DeviceCopy, XilPdi_MetaHdr::FlashOfstAddr, XilPdi_MetaHdr::ImgHdrTable, XilPdi_ImgHdrTable::NoOfPrtns, XilPdi_MetaHdr::PrtnHdr, and XilPdi_PrtnHdr::TotalDataWordLen.
XStatus XilPdi_ReadAndVerifyImgHdr (XilPdi_MetaHdr * MetaHdrPtr)
This function reads and verifies the image header.
Parameters
MetaHdrPtr is pointer to the XilPdi_MetaHdr structure
Returns
XST_SUCCESS on successful validation of image header
errors as mentioned in xilpdi.h
Note
Read the Img headers of 64 bytes and update the image header structure for all images
References XilPdi_MetaHdr::DeviceCopy, XilPdi_MetaHdr::FlashOfstAddr, XilPdi_MetaHdr::ImgHdr, XilPdi_ImgHdrTable::ImgHdrAddr, XilPdi_MetaHdr::ImgHdrTable, XilPdi_ImgHdrTable::NoOfImgs, and XilPdi_ValidateChecksum().
XStatus XilPdi_ReadAndVerifyPrtnHdr (XilPdi_MetaHdr * MetaHdrPtr)
This function reads and verifies the partition header.
Parameters
MetaHdrPtr is pointer to the XilPdi_MetaHdr structure
Returns
XST_SUCCESS on successful validation of partition header
errors as mentioned in xilpdi.h
Note
Read the Img header table of 64 bytes and update the image header table structure
References XilPdi_MetaHdr::DeviceCopy, XilPdi_MetaHdr::FlashOfstAddr, XilPdi_MetaHdr::ImgHdrTable, XilPdi_PrtnHdr::NextPrtnOfst, XilPdi_ImgHdrTable::NoOfPrtns, XilPdi_MetaHdr::PrtnHdr, XilPdi_ImgHdrTable::PrtnHdrAddr, and XilPdi_ValidateChecksum().
XStatus XilPdi_ReadBootHdr (XilPdi_MetaHdr * MetaHdrPtr)
This function reads the boot header.
Parameters
MetaHdrPtr is pointer to the XilPdi_MetaHdr structure
Returns
XST_SUCCESS on successful reading of meta header
errors as mentioned in xilpdi.h
Note
Print FW Rsvd fields Details
References XilPdi_MetaHdr::BootHdr, XilPdi_BootHdr::BootHdrFwRsvd, XilPdi_BootHdr::ImgAttrb, XilPdi_BootHdrFwRsvd::MetaHdrAcOfst, XilPdi_BootHdrFwRsvd::MetaHdrLen, XilPdi_BootHdrFwRsvd::MetaHdrOfst, and XilPdi_BootHdr::WidthDetection.
XStatus XilPdi_ReadImgHdrTbl (XilPdi_MetaHdr * MetaHdrPtr)
This function Reads the image header table.
Parameters
MetaHdrPtr is pointer to the XilPdi_MetaHdr structure
Returns
XST_SUCCESS on successful reading
errors as mentioned in xilpdi.h
Note
Read the Img header table of 64 bytes and update the image header table structure
References XilPdi_MetaHdr::BootHdr, XilPdi_BootHdr::BootHdrFwRsvd, XilPdi_MetaHdr::DeviceCopy, XilPdi_MetaHdr::FlashOfstAddr, XilPdi_MetaHdr::ImgHdrTable, and XilPdi_BootHdrFwRsvd::MetaHdrOfst.
XStatus XilPdi_ValidateChecksum (u32 Buffer[], u32 Len)
This function is used to validate the word checksum for the image header table and partition headers.
Checksum is based on the below formulae Checksum = ~(X1 + X2 + X3 + .... + Xn)
Parameters
Buffer pointer for the data words.
Len of the buffer for which checksum should be calculated. last word is taken as checksum for the data to be compared against
Returns
XST_SUCCESS for successful checksum validation
XST_FAILURE if checksum validation fails
Note
Checksum = ~(X1 + X2 + X3 + .... + Xn) Calculate the checksum
Read the word from the header
Referenced by XilPdi_ReadAndVerifyImgHdr(), XilPdi_ReadAndVerifyPrtnHdr(), and XilPdi_ValidateImgHdrTable().
XStatus XilPdi_ValidateImgHdrTable (XilPdi_ImgHdrTable * ImgHdrTable)
This function checks the fields of the image header table and validates them.
Img header table contains the fields that common across the partitions and for image
Parameters
ImgHdrTable pointer to the image header table.
Returns
XST_SUCCESS on successful image header table validation
errors as mentioned in xilpdi.h
Note
Print the Img header table details Print the Bootgen version
References XilPdi_ImgHdrTable::Attr, XilPdi_ImgHdrTable::Idcode, XilPdi_ImgHdrTable::ImgHdrAddr, XilPdi_ImgHdrTable::NoOfImgs, XilPdi_ImgHdrTable::NoOfPrtns, XilPdi_ImgHdrTable::PrtnHdrAddr, XilPdi_ImgHdrTable::SBDAddr, XilPdi_ImgHdrTable::Version, XILPDI_ERR_IHT_CHECKSUM, and XilPdi_ValidateChecksum().
XStatus XilPdi_ValidatePrtnHdr (XilPdi_PrtnHdr * PrtnHdr)
This function validates the partition header.
Parameters
PrtnHdr is pointer to the XilPdi_PrtnHdr structure
Returns
XST_SUCCESS on successful partition header validation
errors as mentioned in xilpdi.h
Note
Print Prtn Hdr Details
References XilPdi_PrtnHdr::DstnExecutionAddr, XilPdi_PrtnHdr::DstnLoadAddr, XilPdi_PrtnHdr::EncDataWordLen, XilPdi_PrtnHdr::PrtnAttrb, XilPdi_PrtnHdr::TotalDataWordLen, and XilPdi_PrtnHdr::UnEncDataWordLen.