xilsecure_v4_1: XILSECURE_UTILITIES
XILSECURE_UTILITIES
Functions
void XSecure_SetReset (u32 BaseAddress, u32 Offset)
This function places the hardware core into the reset.
void XSecure_ReleaseReset (u32 BaseAddress, u32 Offset)
This function takes the hardware core out of reset.
void XSecure_SssInitialize (XSecure_Sss *InstancePtr)
This function initializes the secure stream switch instance.
u32 XSecure_SssAes (XSecure_Sss *InstancePtr, XSecure_SssSrc InputSrc, XSecure_SssSrc OutputSrc)
This function configures the secure stream switch for AES engine.
u32 XSecure_SssSha (XSecure_Sss *InstancePtr, u16 DmaId)
This function configures the secure stream switch for SHA hardware engine.
u32 XSecure_SssDmaLoopBack (XSecure_Sss *InstancePtr, u16 DmaId)
This function configures secure stream switch to set DMA in loop back mode.
Function Documentation
void XSecure_ReleaseReset (u32 BaseAddress, u32 Offset)
This function takes the hardware core out of reset.
Parameters
BaseAddress Base address of the core.
BaseAddress Offset of the reset register.
Returns
None
Referenced by XSecure_AesReset(), and XSecure_Sha3Start().
void XSecure_SetReset (u32 BaseAddress, u32 Offset)
This function places the hardware core into the reset.
Parameters
BaseAddress Base address of the core.
BaseAddress Offset of the reset register.
Returns
None
Referenced by XSecure_Sha3Finish().
u32 XSecure_SssAes (XSecure_Sss * InstancePtr, XSecure_SssSrc InputSrc, XSecure_SssSrc OutputSrc)
This function configures the secure stream switch for AES engine.
Parameters
InstancePtr Instance pointer to the XSecure_Sss
InputSrc Input DMA to be selected for AES engine.
OutputSrc Output DMA to be selected for AES engine.
Returns
- XST_SUCCESS - on successful configuration of the switch
Note
InputSrc, OutputSrc are of type XSecure_SssSrc.
Referenced by XSecure_AesDecrypt(), XSecure_AesDecryptInit(), and XSecure_AesEncryptInit().
u32 XSecure_SssDmaLoopBack (XSecure_Sss * InstancePtr, u16 DmaId)
This function configures secure stream switch to set DMA in loop back mode.
Parameters
InstancePtr Instance pointer to the XSecure_Sss
DmaId Device ID of DMA.
Returns
- XST_SUCCESS - on successful configuration of the switch.
Referenced by XSecure_MemCopy().
void XSecure_SssInitialize (XSecure_Sss * InstancePtr)
This function initializes the secure stream switch instance.
Parameters
InstancePtr Instance pointer to the XSecure_Sss.
Referenced by XSecure_AesInitialize(), XSecure_MemCopy(), and XSecure_Sha3Initialize().
u32 XSecure_SssSha (XSecure_Sss * InstancePtr, u16 DmaId)
This function configures the secure stream switch for SHA hardware engine.
Parameters
InstancePtr Instance pointer to the XSecure_Sss
DmaId Device ID of DMA which is to be used as an input to the SHA engine.
Returns
- XST_SUCCESS - on successful configuration of the switch.
Referenced by XSecure_Sha3Finish().