xilloader_v1_0: xloader_secure.c File Reference
xloader_secure.c File Reference
Overview
This file contains all security functionality operations.
MODIFICATION HISTORY:
Ver   Who  Date     Changes
----- ---- -------- -------------------------------------------------------
1.0   vns  04/23/19 First release
Note
Functions
u32 XLoader_SecureInit (XLoader_SecureParms *SecurePtr, XilPdi *PdiPtr, u32 PrtnNum)
This function initializes XLoader_SecureParms's instance.
u32 XLoader_SecureCopy (XLoader_SecureParms *SecurePtr, u64 DestAddr, u32 Size)
This function loads secure non-cdo partitions.
u32 XLoader_SecurePrtn (XLoader_SecureParms *SecurePtr, u64 DstAddr, u32 BlockSize, u8 Last)
This function performs authentication, checksum and decryption of the partition.
u32 XLoader_SecureValidations (XLoader_SecureParms *SecurePtr)
This function checks if authentication/encryption is compulsory.
u32 XLoader_ImgHdrTblAuth (XLoader_SecureParms *SecurePtr, XilPdi_ImgHdrTable *ImgHdrTbl)
This function checks if authentication/encryption is compulsory and authenticates the image header table if authentication is enabled.
u32 XLoader_ReadAndVerifySecureHdrs (XLoader_SecureParms *SecurePtr, XilPdi_MetaHdr *MetaHdr)
This function authenticates and/or decrypts the image headers and partition headers and copies the contents to corresponding structures.
Function Documentation
u32 XLoader_ImgHdrTblAuth (XLoader_SecureParms * SecurePtr, XilPdi_ImgHdrTable * ImgHdrTbl)
This function checks if authentication/encryption is compulsory and authenticates the image header table if authentication is enabled.
Parameters
SecurePtr Pointer to the XLoader_SecureParms instance.
ImgHdrTbl Pointer to the image header table.
Returns
XST_SUCCESS on success.
Referenced by XLoader_PdiInit().
u32 XLoader_ReadAndVerifySecureHdrs (XLoader_SecureParms * SecurePtr, XilPdi_MetaHdr * MetaHdr)
This function authenticates and/or decrypts the image headers and partition headers and copies the contents to corresponding structures.
Parameters
SecurePtr Pointer to the XLoader_SecureParms instance.
MetaHdr Pointer to the Meta header table.
Returns
XST_SUCCESS on success.
Referenced by XLoader_PdiInit().
u32 XLoader_SecureCopy (XLoader_SecureParms * SecurePtr, u64 DestAddr, u32 Size)
This function loads secure non-cdo partitions.
Parameters
SecurePtr Pointer to the XLoader_SecureParms instance.
DestAddr Load address of the partition
Size un encrypted size of the partition.
Returns
XST_SUCCESS on success.
Update the length for last chunk
References XLoader_SecurePrtn().
u32 XLoader_SecureInit (XLoader_SecureParms * SecurePtr, XilPdi * PdiPtr, u32 PrtnNum)
This function initializes XLoader_SecureParms's instance.
Parameters
SecurePtr Pointer to the XLoader_SecureParms instance.
PdiPtr Pointer to the XilPdi.
PrtnNum Partition number to be processed.
Returns
XST_SUCCESS on success.
References XilPdi::MetaHdr.
u32 XLoader_SecurePrtn (XLoader_SecureParms * SecurePtr, u64 DstAddr, u32 BlockSize, u8 Last)
This function performs authentication, checksum and decryption of the partition.
Parameters
SecurePtr Pointer to the XLoader_SecureParms instance.
BlockSize Size of the data block to be processed which doesn't include padding lengths and hash.
Last Notifies if the block to be processed is last or not.
Returns
XST_SUCCESS on success.
Note
If Size < chunk size it is first block If last = TRUE then last chunk
Referenced by XLoader_SecureCopy().
u32 XLoader_SecureValidations (XLoader_SecureParms * SecurePtr)
This function checks if authentication/encryption is compulsory.
Parameters
SecurePtr Pointer to the XLoader_SecureParms instance.
Returns
XST_SUCCESS on success.
Referenced by XLoader_PdiInit().