xilloader_v1_0: xloader.c File Reference
xloader.c File Reference
Overview
This file contains the code related to PDI image loading.
MODIFICATION HISTORY:
Ver   Who  Date        Changes
----- ---- -------- -------------------------------------------------------
1.00  kc   07/25/2018 Initial release
Note
Functions
int XLoader_Init ()
This function initializes the loader instance and registers loader commands with PLM.
int XLoader_PdiInit (XilPdi *PdiPtr, u32 PdiSrc, u64 PdiAddr)
This function initializes the PDI instance with required details and read the meta header.
int XLoader_LoadAndStartSubSystemPdi (XilPdi *PdiPtr)
This function is used to load and start the PDI image.
int XLoader_LoadPdi (XilPdi *PdiPtr, u32 PdiSrc, u64 PdiAddr)
This function provides loading PDI.
int XLoader_StartImage (XilPdi *PdiPtr)
This function is used to start the subsystems in the PDI.
void XLoader_A72Config (u32 CpuId, u32 ExecState, u32 VInitHi)
This function is used to perform Aarch state and vector location for APU.
int XLoader_LoadImage (XilPdi *PdiPtr, u32 ImageId)
This function is used load a image in PDI.
int XLoader_RestartImage (u32 ImageId)
This function is used to restart the image in PDI.
int XLoader_ReloadImage (u32 ImageId)
This function is used to reload the image only in PDI.
Function Documentation
void XLoader_A72Config (u32 CpuId, u32 ExecState, u32 VInitHi)
This function is used to perform Aarch state and vector location for APU.
Parameters
CpuId CPU ID
ExecState CPU execution state
VinitHi VinitHi configuration for CPU
Returns
None
Referenced by XLoader_StartImage().
int XLoader_Init ()
This function initializes the loader instance and registers loader commands with PLM.
Parameters
None
Returns
returns XST_SUCCESS on success
Initializes the DMA pointers
Initialize the loader commands
Initialize the loader interrupts
References XLoader_CframeInit(), XLoader_CmdsInit(), and XLoader_IntrInit().
int XLoader_LoadAndStartSubSystemPdi (XilPdi * PdiPtr)
This function is used to load and start the PDI image.
It reads meta header, loads the images as present in the PDI and starts based on hand-off information present in PDI
Parameters
PdiPtr Pdi instance pointer
Returns
returns XLOADER_SUCCESS on success
From the meta header present in PDI pointer, read the subsystem image details and load, start all the images
For every image,
Read the CDO file if present
Send the CDO file to cdo parser which directs CDO commands to Xilpm, and other components
Load partitions to respective memories
Check for Cfi errors
Set the Secondary Boot Mode settings to enable the read from the secondary device
Mark PDI loading is completed
References XilPdi::ImageNum, XilPdi::MetaHdr, XilSubsystem::PdiPtr, XilPdi::PdiType, XLoader_CfiErrorHandler(), XLoader_LoadImage(), XLoader_LoadPdi(), and XLoader_StartImage().
Referenced by XLoader_LoadPdi().
int XLoader_LoadImage (XilPdi * PdiPtr, u32 ImageId)
This function is used load a image in PDI.
PDI can have multiple images present in it. This can be used to load a single image like PL, APU, RPU. This will load all the partitions that are present in that image.
Parameters
PdiPtr Pdi instance pointer
ImageId Id of the image present in PDI
Returns
returns XLOADER_SUCCESS on success
References XilSubsystem::Count, XilPdi::CurImgId, XilPdi::ImageNum, XilSubsysInfo::ImageNum, XilPdi::MetaHdr, XilPdi::PdiType, XilPdi::PrtnNum, XilSubsysInfo::PrtnNum, XilSubsysInfo::SubsystemId, XilSubsystem::SubsystemLut, and XLoader_LoadImagePrtns().
Referenced by XLoader_LoadAndStartSubSystemPdi(), and XLoader_ReloadImage().
int XLoader_LoadPdi (XilPdi * PdiPtr, u32 PdiSrc, u64 PdiAddr)
This function provides loading PDI.
Parameters
Pdi instance pointer where PDI details are stored
PdiSrc is source of PDI. It can be in Boot Device, DDR
PdiAddr is the address at PDI is located in the PDI source mentioned
Returns
Returns the Load PDI command
Reset the SBI to clear the buffer in case of error
References XLoader_LoadAndStartSubSystemPdi(), and XLoader_PdiInit().
Referenced by XLoader_LoadAndStartSubSystemPdi(), and XLoader_SbiLoadPdi().
int XLoader_PdiInit (XilPdi * PdiPtr, u32 PdiSrc, u64 PdiAddr)
This function initializes the PDI instance with required details and read the meta header.
Parameters
Pdi instance pointer where PDI details are stored
PdiSrc is source of PDI. It can be in Boot Device, DDR
PdiAddr is the address at PDI is located in the PDI source mentioned
Returns
returns XLOADER_SUCCESS on success
Update PDI Ptr with source, addr, meta header
Mark PDI loading is started.
Read meta header from PDI source
Check the validity of Img Hdr Table fields
References XilPdi::ImageNum, XilPdi::MetaHdr, XilPdi::PdiAddr, XilPdi::PdiSrc, XilPdi::PdiType, XilPdi::PrtnNum, XLoader_ImgHdrTblAuth(), XLoader_ReadAndVerifySecureHdrs(), and XLoader_SecureValidations().
Referenced by XLoader_LoadPdi().
int XLoader_ReloadImage (u32 ImageId)
This function is used to reload the image only in PDI.
This function will take ImageId as an input and based on the subsystem info available, it will read the image partitions and loads them.
Parameters
ImageId Id of the image present in PDI
Returns
returns XLOADER_SUCCESS on success
This is for libpm to do the clock settings reqired for boot device to resume post suspension.
References XilSubsystem::PdiPtr, XilPdi::PdiSrc, and XLoader_LoadImage().
Referenced by XLoader_RestartImage().
int XLoader_RestartImage (u32 ImageId)
This function is used to restart the image in PDI.
This function will take ImageId as an input and based on the subsystem info available, it will read the image partitions, loads them and hand-off to the required CPUs as part of the image load.
Parameters
ImageId Id of the image present in PDI
Returns
returns XLOADER_SUCCESS on success
References XilSubsystem::PdiPtr, XLoader_ReloadImage(), and XLoader_StartImage().
int XLoader_StartImage (XilPdi * PdiPtr)
This function is used to start the subsystems in the PDI.
Parameters
PdiPtr Pdi instance pointer
Returns
returns XLOADER_SUCCESS on success
References XilPdi::NoOfHandoffCpus, and XLoader_A72Config().
Referenced by XLoader_LoadAndStartSubSystemPdi(), and XLoader_RestartImage().