xilplmi_v1_0: xplmi_task.h File Reference
xplmi_task.h File Reference
Overview
This is the file which contains command execution code.
MODIFICATION HISTORY:
Ver   Who  Date        Changes
----- ---- -------- -------------------------------------------------------
1.00  kc   02/06/2019 Initial release
Note
Macros
#define metal_offset_of(structure, member) ((uintptr_t) &(((structure *) 0)->member))
Compute offset of a field within a structure.
#define metal_container_of(ptr, structure, member) (void *)((uintptr_t)(ptr) - metal_offset_of(structure, member))
Compute pointer to a structure given a pointer to one of its fields.
Functions
XPlmi_TaskNode * XPlmi_TaskCreate (u32 Priority, int(*Handler)(void *PrivData), void *PrivData)
This function creates the task and initializes its fields with the user parameters.
void XPlmi_TaskDelete (XPlmi_TaskNode *Task)
This function deletes the task from the task queue.
void XPlmi_TaskTriggerNow (XPlmi_TaskNode *Task)
This function adds the task to the task queue so that it can be triggered based on its priority.
void XPlmi_TaskInit (void)
This function initializes the task queues list.
void XPlmi_TaskDispatchLoop (void)
This function will be checking for tasks in the queue based on the priority.
Macro Definition Documentation
#define metal_container_of (ptr, structure, member) (void *)((uintptr_t)(ptr) - metal_offset_of(structure, member))
Compute pointer to a structure given a pointer to one of its fields.
Referenced by XPlmi_TaskDispatchLoop().
#define metal_offset_of (structure, member) ((uintptr_t) &(((structure *) 0)->member))
Compute offset of a field within a structure.
Function Documentation
XPlmi_TaskNode* XPlmi_TaskCreate (u32 Priority, int(*)(void *PrivData) Handler, void * PrivData)
This function creates the task and initializes its fields with the user parameters.
Parameters
Priority Priority of the task
handler function pointer to the task handler
PrivData Private Data to be passed with task handler
Returns
Pointer to the task node structure
Assign free task node
void XPlmi_TaskDelete (XPlmi_TaskNode * Task)
This function deletes the task from the task queue.
Parameters
Task Pointer to the task node
Returns
None
Referenced by XPlmi_TaskDispatchLoop().
void XPlmi_TaskDispatchLoop (void)
This function will be checking for tasks in the queue based on the priority.
After calling every task handlers, next high priority task will be called.
Parameters
None
Returns
None
Priority based task handling
if no pending tasks are present, go to sleep
Get the task
delete the task that is handled
TODO Call the error manager
Goto sleep when all queues are empty
References metal_container_of, XPlmi_ErrMgr(), XPlmi_GetTimerValue(), XPlmi_MeasurePerfTime(), and XPlmi_TaskDelete().
void XPlmi_TaskInit (void)
This function initializes the task queues list.
Parameters
None
Returns
None
void XPlmi_TaskTriggerNow (XPlmi_TaskNode * Task)
This function adds the task to the task queue so that it can be triggered based on its priority.
Parameters
Task Pointer to the task node
Returns
None