xilplmi_v1_0: xplmi_gic_interrupts.c File Reference
xplmi_gic_interrupts.c File Reference
Overview
This file is to handle the GIC interrupts.
MODIFICATION HISTORY:
Ver   Who  Date        Changes
====  ==== ======== ======================================================-
1.00  mg   10/08/2018 Initial release
Note
Functions
void XPlmi_GicRegisterHandler (u32 PlmIntrId, Function_t Handler, void *Data)
This will register the GIC handler.
void XPlmi_GicIntrEnable (u32 PlmIntrId)
This will enable the GIC interrupt.
void XPlmi_GicIntrDisable (u32 PlmIntrId)
This will disable the GIC interrupt.
void XPlmi_GicIntrHandler (void *CallbackRef)
This is handler for GIC interrupts.
int XPlmi_DispatchWakeHandler (void *DeviceIdx)
This is the handler for wake up interrupts.
Function Documentation
int XPlmi_DispatchWakeHandler (void * DeviceIdx)
This is the handler for wake up interrupts.
Parameters
DeviceIdx Index of peripheral device
Returns
Status XST_SUCCESS if processor wake successfully XST_FAILURE or error code in case of failure
void XPlmi_GicIntrDisable (u32 PlmIntrId)
This will disable the GIC interrupt.
Parameters
None
Returns
None
Get the GicP mask
References PMC_GLOBAL_GICP0_IRQ_DISABLE, and XPlmi_UtilRMW().
Referenced by XPlmi_PlmIntrDisable().
void XPlmi_GicIntrEnable (u32 PlmIntrId)
This will enable the GIC interrupt.
Parameters
None
Returns
None
Get the GicP mask
References PMC_GLOBAL_GICP0_IRQ_ENABLE, PMC_GLOBAL_GICP_PMC_IRQ_ENABLE, and XPlmi_UtilRMW().
Referenced by XPlmi_PlmIntrEnable().
void XPlmi_GicIntrHandler (void * CallbackRef)
This is handler for GIC interrupts.
Parameters
CallbackRef is presently the interrupt number that is received
Returns
void
void XPlmi_GicRegisterHandler (u32 PlmIntrId, Function_t Handler, void * Data)
This will register the GIC handler.
Parameters
None
Returns
None
Get the GicP mask
Register Handler
Referenced by XPlmi_RegisterHandler().