xilplmi_v1_0: xplmi_proc.h File Reference
xplmi_proc.h File Reference
Overview
This file contains declarations for PROC C file in PLM.
MODIFICATION HISTORY:
Ver   Who  Date        Changes
----- ---- -------- -------------------------------------------------------
1.00  kc   02/07/2019 Initial release
Note
Enumerations
enum
PMC IOmodule interrupts.
enum
External interrupt mapping.
Functions
void XPlmi_InitPitTimer (u8 Timer, u32 ResetValue)
It initializes the Programmable Interval Timer.
int XPlmi_StartTimer ()
It initializes the IO module strutures and PIT timers.
void XPlmi_IntrHandler (void *CallbackRef)
This function is default interrupt handler for the device.
u64 XPlmi_GetTimerValue (void)
This function is used to read the 64 bit timer value.
int XPlmi_SetUpInterruptSystem ()
This function connects the interrupt handler of the IO Module to the processor.
void XPlmi_MeasurePerfTime (u64 tCur)
This function measures the total time taken between two points for performance measurement.
void XPlmi_PlmIntrEnable (u32 IntrId)
This function will enable the interrupt.
void XPlmi_PlmIntrDisable (u32 IntrId)
This function will disable the interrupt.
void XPlmi_RegisterHandler (u32 IntrId, Function_t Handler, void *Data)
This function will register the handler and enable the interrupt.
void XPlmi_PrintRomTime ()
This function prints the ROM time.
void XPlmi_PrintPlmTimeStamp ()
This function prints the PLM time stamp.
Enumeration Type Documentation
anonymous enum
PMC IOmodule interrupts.
anonymous enum
External interrupt mapping.
Function Documentation
u64 XPlmi_GetTimerValue (void)
This function is used to read the 64 bit timer value.
It reads from PIT1 and PIT2 and makes it 64bit
Parameters
None
Returns
Returns 64 bit timer value
Pit1 starts at 0 and preload the full value after pit2 expires. So, recasting TPit1 0 value to highest so that u64 comparison works fo Tpit1 0 and TPit1 0xfffffffe
Referenced by XPlmi_MeasurePerfTime(), and XPlmi_TaskDispatchLoop().
void XPlmi_InitPitTimer (u8 Timer, u32 ResetValue)
It initializes the Programmable Interval Timer.
Parameters
TimerNo PIT Timer to be initialized
ResetValue is the reset value of timer when started
Returns
None
Referenced by XPlmi_StartTimer().
void XPlmi_IntrHandler (void * CallbackRef)
This function is default interrupt handler for the device.
Parameters
CallbackRef is presently the interrupt number that is received
Returns
None.
Indicate Interrupt received
void XPlmi_MeasurePerfTime (u64 tCur)
This function measures the total time taken between two points for performance measurement.
Parameters
Start time
Returns
none
References XPlmi_GetTimerValue(), and XPlmi_PrintTime().
Referenced by XPlmi_PrintPlmTimeStamp(), and XPlmi_TaskDispatchLoop().
void XPlmi_PlmIntrDisable (u32 IntrId)
This function will disable the interrupt.
Parameters
IntrId Interrupt ID as specified in the xplmi_proc.h
Returns
None.
References XPlmi_GicIntrDisable().
void XPlmi_PlmIntrEnable (u32 IntrId)
This function will enable the interrupt.
Parameters
IntrId Interrupt ID as specified in the xplmi_proc.h
Returns
None.
References XPlmi_GicIntrEnable().
Referenced by XPlmi_SysMonInit().
void XPlmi_PrintPlmTimeStamp ()
This function prints the PLM time stamp.
Parameters
none
Returns
none
References XPlmi_MeasurePerfTime().
void XPlmi_PrintRomTime ()
This function prints the ROM time.
Parameters
none
Returns
none
Get PMC ROM time
References PMC_GLOBAL_GLOBAL_GEN_STORAGE0, PMC_GLOBAL_GLOBAL_GEN_STORAGE1, and XPlmi_PrintTime().
void XPlmi_RegisterHandler (u32 IntrId, Function_t Handler, void * Data)
This function will register the handler and enable the interrupt.
Parameters
IntrId Interrupt ID as specified in the xplmi_proc.h
Handler Handler to the registered for the interrupt
Data Data to be passed to handler
Returns
None.
References XPlmi_GicRegisterHandler().
Referenced by XPlmi_SysMonInit().
int XPlmi_SetUpInterruptSystem ()
This function connects the interrupt handler of the IO Module to the processor.
Parameters
None.
Returns
XST_SUCCESS if handlers are registered properly
Enable interrupts for the device and then cause interrupts so the handlers will be called.
Register the IO module interrupt handler with the exception table.
Enable interrupts
Clear Break In Progress to get interrupts
Referenced by XPlmi_Init().
int XPlmi_StartTimer ()
It initializes the IO module strutures and PIT timers.
Returns
XST_SUCCESS if the initialization is successful
Initialize and start the timer Use PIT1 and PIT2 in prescalor mode
References XPlmi_InitPitTimer().