xilplmi_v1_0: xplmi_status.h File Reference
xplmi_status.h File Reference
Overview
This is the header file which contains status codes for the PLM, PLMI and loader.
MODIFICATION HISTORY:
Ver   Who  Date        Changes
----- ---- -------- -------------------------------------------------------
1.00  kc   07/13/2018 Initial release
Note
PLM error codes description
0xXXXXYYYY - Error code format XXXX - PLM/LOADER/XPLMI error codes as defined in xplmi_status.h YYYY - Libraries / Drivers error code as defined in respective modules
#define XPLMI_SUCCESS (XST_SUCCESS)
#define XPLMI_CORRECTABLE_ERROR_MASK (1U<<31U)
#define XPLMI_UNCORRECTABLE_ERROR_MASK (1U<<30U)
#define XPLMI_STATUS_MASK (0xFFFF0000U)
#define XPLMI_STATUS_MODULE_MASK (0xFFFFU)
#define XPLMI_UPDATE_STATUS(PlmiStatus, ModuleStatus)
enum { XPLM_SUCCESS = 0x0 , XPLM_ERR_TASK_CREATE = 0x200 , XLOADER_UNSUPPORTED_BOOT_MODE = 0x300 }
Status for PLM functions.
void XPlmi_ErrMgr (int Status)
This function is called in PLM error cases.
void XPlmi_DumpRegisters ()
This function dumps the registers which can help debugging.
Enumeration Type Documentation
anonymous enum
Status for PLM functions.
Enumerator
XPLM_SUCCESS
Status codes used in PLMI.
XPLM_ERR_TASK_CREATE
Status codes used in PLM.
XLOADER_UNSUPPORTED_BOOT_MODE
Status codes used in XLOADER.
Function Documentation
void XPlmi_DumpRegisters ()
This function dumps the registers which can help debugging.
Parameters
@return none
Note
none
References PMC_GLOBAL_GICP0_IRQ_STATUS, PMC_GLOBAL_GICP1_IRQ_STATUS, PMC_GLOBAL_GICP2_IRQ_STATUS, PMC_GLOBAL_GICP3_IRQ_STATUS, PMC_GLOBAL_GICP4_IRQ_STATUS, PMC_GLOBAL_GICP5_IRQ_STATUS, PMC_GLOBAL_GICP6_IRQ_STATUS, PMC_GLOBAL_GICP7_IRQ_STATUS, PMC_GLOBAL_GICP_PMC_IRQ_STATUS, PMC_GLOBAL_PMC_ERR1_STATUS, PMC_GLOBAL_PMC_ERR2_STATUS, PMC_GLOBAL_PMC_FW_ERR, PMC_GLOBAL_PMC_GSW_ERR, PMC_GLOBAL_PMC_MULTI_BOOT, and PMC_GLOBAL_PWR_STATUS.
Referenced by XPlmi_ErrMgr().
void XPlmi_ErrMgr (int Status)
This function is called in PLM error cases.
Parameters
ErrorStatus is the error code which is written to the error status register
Returns
none
Fallback if boot PDI is not done else just return, so that we receive next requests
TODO Add fallback code here.
References PMC_GLOBAL_PMC_FW_ERR, and XPlmi_DumpRegisters().
Referenced by XPlmi_TaskDispatchLoop().