xilplmi_v1_0: xplmi_dma.c File Reference
xplmi_dma.c File Reference
Overview
This is the file which contains PMC DMA interface code for the PLM.
MODIFICATION HISTORY:
Ver   Who  Date        Changes
----- ---- -------- -------------------------------------------------------
1.00  kc   12/21/2018 Initial release
Note
Functions
int XPlmi_DmaDrvInit (XCsuDma *DmaPtr, u32 DeviceId)
This function is used to initialize a single Driver instance.
int XPlmi_DmaInit ()
This function will initialize the DMA driver instances.
XCsuDma * XPlmi_GetDmaInstance (u32 DeviceId)
This function returns DMA instance.
void XPlmi_SSSCfgDmaDma (u32 Flags)
This function is used set SSS configuration for DMA to DMA.
void XPlmi_SSSCfgSbiDma (u32 Flags)
This function is used set SSS configuration for SBI to DMA.
void XPlmi_SSSCfgDmaPzm (u32 Flags)
This function is used set SSS configuration for DMA to PZM.
void XPlmi_SSSCfgDmaSbi (u32 Flags)
This function is used set SSS configuration for DMA to SBI transfer.
int XPlmi_DmaChXfer (u64 Addr, u32 Len, XCsuDma_Channel Channel, u32 Flags)
This function is used transfer the data on SRC or DST channel.
int XPlmi_SbiDmaXfer (u64 DestAddr, u32 Len, u32 Flags)
This function is used to transfer the data from SBI to DMA.
int XPlmi_DmaSbiXfer (u64 SrcAddr, u32 Len, u32 Flags)
This function is used to transfer the data from DMA to SBI.
int XPlmi_DmaXfr (u64 SrcAddr, u64 DestAddr, u32 Len, u32 Flags)
This function is used to initiate and complete the DMA to DMA transfer.
int XPlmi_StartDma (u64 SrcAddr, u64 DestAddr, u32 Len, u32 Flags, XCsuDma **DmaPtrAddr)
This function is used initiate the DMA to DMA transfer.
int XPlmi_EccInit (u64 Addr, u32 Len)
This function is used to ECC initialize the memory.
Variables
XCsuDma CsuDma0
Instance of the Csu_Dma Device.
XCsuDma CsuDma1
Instance of the Csu_Dma Device.
Function Documentation
int XPlmi_DmaChXfer (u64 Addr, u32 Len, XCsuDma_Channel Channel, u32 Flags)
This function is used transfer the data on SRC or DST channel.
Parameters
Addr Address to which data has to be stored
Len Length of the data in bytes
Channel SRC/DST channel selection
Flags Flags to select PMC DMA and DMA Burst type
Returns
Error Codes
References CsuDma0, CsuDma1, and XPLMI_SRC_CH_AXI_FIXED.
Referenced by XPlmi_DmaSbiXfer(), XPlmi_EccInit(), and XPlmi_SbiDmaXfer().
int XPlmi_DmaDrvInit (XCsuDma * DmaPtr, u32 DeviceId)
This function is used to initialize a single Driver instance.
Parameters
DmaPtr Pointer to the DMA instance
DeviceId Device ID of the DMA as defined in xparameters.h
Returns
Error Codes
Referenced by XPlmi_DmaInit().
int XPlmi_DmaInit ()
This function will initialize the DMA driver instances.
Returns
Error Codes
References CsuDma0, CsuDma1, and XPlmi_DmaDrvInit().
int XPlmi_DmaSbiXfer (u64 SrcAddr, u32 Len, u32 Flags)
This function is used to transfer the data from DMA to SBI.
Parameters
SrcAddr Source address for DMA to fetch data from
Len Length of the data in bytes
Flags Flags to select PMC DMA and DMA Burst type
Returns
Error codes
References XPlmi_DmaChXfer(), and XPlmi_SSSCfgDmaSbi().
Referenced by XPlmi_CfiRead().
int XPlmi_DmaXfr (u64 SrcAddr, u64 DestAddr, u32 Len, u32 Flags)
This function is used to initiate and complete the DMA to DMA transfer.
Parameters
SrcAddr Address for SRC channel to fetch data from
DestAddr Address for DST channel to store the data
Len Length of the data in bytes
Flags Flags to select PMC DMA and DMA Burst type
Returns
Error codes
References XPLMI_SRC_CH_AXI_FIXED, and XPlmi_StartDma().
Referenced by XPlmi_CfiRead(), XPlmi_DmaWriteKeyHole(), and XPlmi_NpiRead().
int XPlmi_EccInit (u64 Addr, u32 Len)
This function is used to ECC initialize the memory.
Parameters
Addr Memory address to be initialized
Len Length of the area to be initialized in bytes
Returns
References PMC_GLOBAL_PRAM_ZEROIZE_SIZE, XPlmi_DmaChXfer(), and XPlmi_SSSCfgDmaPzm().
XCsuDma* XPlmi_GetDmaInstance (u32 DeviceId)
This function returns DMA instance.
Parameters
DeviceId PMC DMA's device ID
Returns
PMC DMA instance pointer.
References CsuDma0, and CsuDma1.
int XPlmi_SbiDmaXfer (u64 DestAddr, u32 Len, u32 Flags)
This function is used to transfer the data from SBI to DMA.
Parameters
DestAddr Address to which data has to be stored
Len Length of the data in bytes
Flags Flags to select PMC DMA and DMA Burst type
Returns
Error Codes
References XPlmi_DmaChXfer(), and XPlmi_SSSCfgSbiDma().
void XPlmi_SSSCfgDmaDma (u32 Flags)
This function is used set SSS configuration for DMA to DMA.
Parameters
Flags Flags to select PMC DMA
Returns
none
References PMC_GLOBAL_PMC_SSS_CFG, and XPlmi_UtilRMW().
Referenced by XPlmi_StartDma().
void XPlmi_SSSCfgDmaPzm (u32 Flags)
This function is used set SSS configuration for DMA to PZM.
Parameters
Flags Flags to select PMC DMA
Returns
none
References PMC_GLOBAL_PMC_SSS_CFG, and XPlmi_UtilRMW().
Referenced by XPlmi_EccInit().
void XPlmi_SSSCfgDmaSbi (u32 Flags)
This function is used set SSS configuration for DMA to SBI transfer.
Parameters
Flags Flags to select PMC DMA
Returns
none
References PMC_GLOBAL_PMC_SSS_CFG, and XPlmi_UtilRMW().
Referenced by XPlmi_DmaSbiXfer().
void XPlmi_SSSCfgSbiDma (u32 Flags)
This function is used set SSS configuration for SBI to DMA.
Parameters
Flags Flags to select PMC DMA
Returns
none
References PMC_GLOBAL_PMC_SSS_CFG, and XPlmi_UtilRMW().
Referenced by XPlmi_SbiDmaXfer().
int XPlmi_StartDma (u64 SrcAddr, u64 DestAddr, u32 Len, u32 Flags, XCsuDma ** DmaPtrAddr)
This function is used initiate the DMA to DMA transfer.
Parameters
SrcAddr Address for SRC channel to fetch data from
DestAddr Address for DST channel to store the data
Len Length of the data in bytes
Flags Flags to select PMC DMA and DMA Burst type
Returns
Error codes
References CsuDma0, CsuDma1, XPlmi_PrintArray(), XPLMI_SRC_CH_AXI_FIXED, and XPlmi_SSSCfgDmaDma().
Referenced by XPlmi_DmaXfr().
Variable Documentation
XCsuDma CsuDma0
Instance of the Csu_Dma Device.
Referenced by XPlmi_DmaChXfer(), XPlmi_DmaInit(), XPlmi_GetDmaInstance(), and XPlmi_StartDma().
XCsuDma CsuDma1
Instance of the Csu_Dma Device.
Referenced by XPlmi_DmaChXfer(), XPlmi_DmaInit(), XPlmi_GetDmaInstance(), and XPlmi_StartDma().