xilplmi_v1_0: xplmi_generic.h File Reference
xplmi_generic.h File Reference
Overview
This is the file which contains .
MODIFICATION HISTORY:
Ver   Who  Date        Changes
----- ---- -------- -------------------------------------------------------
1.00  kc   08/23/2018 Initial release
Note
Functions
void XPlmi_GenericInit (void)
This function registers the PLM generic commands to the PLMI.
int XPlmi_CfiRead (XPlmi_Cmd *Cmd)
This function provides CFI READ command execution Command payload parameters are.
int XPlmi_DmaWriteKeyHole (XPlmi_Cmd *Cmd)
This function provides DMA key hole write command execution Command payload parameters are.
Function Documentation
int XPlmi_CfiRead (XPlmi_Cmd * Cmd)
This function provides CFI READ command execution Command payload parameters are.
 * Params - SMPA/JTAG/DDR
 * High Dest Addr
 * Low Dest Addr
 * Read Length in number of words to be read from CFU
 * DATA (CFU READ Packets)
Parameters
Pointer to the command structure
Returns
Returns the Status
Do Nothing
References SLAVE_BOOT_SBI_STATUS, XPlmi_DmaSbiXfer(), XPlmi_DmaXfr(), XPLMI_SRC_CH_AXI_FIXED, XPlmi_UtilPoll(), and XPlmi_UtilRMW().
int XPlmi_DmaWriteKeyHole (XPlmi_Cmd * Cmd)
This function provides DMA key hole write command execution Command payload parameters are.
 * High Dest Addr
 * Low Dest Addr
 * Keyhole Size
 * DATA...
Parameters
Pointer to the command structure
Returns
Returns the Status of DMA Xfer API
store the destination address in resume data
Set DMA flags to DMA0 and FIXED
References XPlmi_DmaXfr().
void XPlmi_GenericInit (void)
This function registers the PLM generic commands to the PLMI.
Parameters
none
Returns
none
Referenced by XPlmi_Init().