xilplmi_v1_0: xplmi_err.c File Reference
xplmi_err.c File Reference
Overview
This file contains error management for the PLM.
MODIFICATION HISTORY:
Ver   Who  Date        Changes
====  ==== ======== ======================================================-
1.00  kc   02/12/2019 Initial release
Note
Functions
void XPlmi_ErrMgr (int Status)
This function is called in PLM error cases.
int XPlmi_EmDisable (u32 ErrorId)
This function disables the responses for the given error ID.
int XPlmi_EmSetAction (u32 ErrorId, u8 ActionId, XPlmi_ErrorHandler_t ErrorHandler)
This function sets the Action specified for a given Error ID.
void XPlmi_EmInit (void)
This function initializes the error module.
void XPlmi_PsEmInit (void)
This function initializes the PSM error actions.
void XPlmi_DumpRegisters ()
This function dumps the registers which can help debugging.
Function Documentation
void XPlmi_DumpRegisters ()
This function dumps the registers which can help debugging.
Parameters
@return none
Note
none
References PMC_GLOBAL_GICP0_IRQ_STATUS, PMC_GLOBAL_GICP1_IRQ_STATUS, PMC_GLOBAL_GICP2_IRQ_STATUS, PMC_GLOBAL_GICP3_IRQ_STATUS, PMC_GLOBAL_GICP4_IRQ_STATUS, PMC_GLOBAL_GICP5_IRQ_STATUS, PMC_GLOBAL_GICP6_IRQ_STATUS, PMC_GLOBAL_GICP7_IRQ_STATUS, PMC_GLOBAL_GICP_PMC_IRQ_STATUS, PMC_GLOBAL_PMC_ERR1_STATUS, PMC_GLOBAL_PMC_ERR2_STATUS, PMC_GLOBAL_PMC_FW_ERR, PMC_GLOBAL_PMC_GSW_ERR, PMC_GLOBAL_PMC_MULTI_BOOT, and PMC_GLOBAL_PWR_STATUS.
Referenced by XPlmi_ErrMgr().
int XPlmi_EmDisable (u32 ErrorId)
This function disables the responses for the given error ID.
Parameters
ErrorId is the error identifier
Returns
Success / failure
References PMC_GLOBAL_PMC_ERR_OUT1_DIS, PMC_GLOBAL_PMC_ERR_OUT2_DIS, PMC_GLOBAL_PMC_IRQ1_DIS, PMC_GLOBAL_PMC_IRQ2_DIS, PMC_GLOBAL_PMC_POR1_DIS, PMC_GLOBAL_PMC_POR2_DIS, PMC_GLOBAL_PMC_SRST1_DIS, and PMC_GLOBAL_PMC_SRST2_DIS.
Referenced by XPlmi_EmSetAction().
void XPlmi_EmInit (void)
This function initializes the error module.
Disables all the error actions and registers default action
Parameters
None
Returns
None
References PMC_GLOBAL_PMC_ERR1_STATUS, PMC_GLOBAL_PMC_ERR2_STATUS, PMC_GLOBAL_PMC_ERR_OUT1_DIS, PMC_GLOBAL_PMC_IRQ1_DIS, PMC_GLOBAL_PMC_POR1_DIS, PMC_GLOBAL_PMC_SRST1_DIS, XPlmi_EmSetAction(), and XPlmi_ErrModuleInit().
int XPlmi_EmSetAction (u32 ErrorId, u8 ActionId, XPlmi_ErrorHandler_t ErrorHandler)
This function sets the Action specified for a given Error ID.
Parameters
ErrorId is the error identifier
ActionId is the action that need to be set for ErrorID. Action can be SRST/POR/ERR OUT/INT
ErrorHandler If INT is defined as response, handler should be defined.
Returns
Success / failure
References XPlmi_EmDisable().
Referenced by XPlmi_EmInit(), and XPlmi_PsEmInit().
void XPlmi_ErrMgr (int Status)
This function is called in PLM error cases.
Parameters
ErrorStatus is the error code which is written to the error status register
Returns
none
Fallback if boot PDI is not done else just return, so that we receive next requests
TODO Add fallback code here.
References PMC_GLOBAL_PMC_FW_ERR, and XPlmi_DumpRegisters().
Referenced by XPlmi_TaskDispatchLoop().
void XPlmi_PsEmInit (void)
This function initializes the PSM error actions.
Disables all the PSM error actions and registers default action
Parameters
None
Returns
None
References PMC_GLOBAL_PMC_ERR1_STATUS, PMC_GLOBAL_PMC_ERR2_STATUS, and XPlmi_EmSetAction().