xilplmi_v1_0: xplmi_util.h File Reference
xplmi_util.h File Reference
Overview
This is the header file PMC FW utilities code.
MODIFICATION HISTORY:
Ver   Who  Date        Changes
----- ---- -------- -------------------------------------------------------
1.00  kc   02/21/2017 Initial release
Note
Functions
void XPlmi_UtilRMW (u32 RegAddr, u32 Mask, u32 Value)
Read Modify Write a register.
int XPlmi_UtilSafetyWrite (u32 RegAddr, u32 Mask, u32 Value)
Writing a value is set of bits to be set (represented by Mask) and reading back the wriiten value to compare that write is sucessfully done.
int XPlmi_UtilPollForMask (u32 RegAddr, u32 Mask, u32 TimeOutCount)
Poll for a set of bits to be set (represented by Mask) or until we TimeOut.
int XPlmi_UtilPoll (u32 RegAddr, u32 Mask, u32 ExpectedValue, u32 TimeOutInUs)
int XPlmi_UtilPoll64 (u64 Addr, u32 Mask, u32 ExpectedValue, u32 TimeOutInUs)
Poll for a set of bits to be cleared (represented by Mask) or until we TimeOut.
int XPlmi_UtilPollForZero (u32 RegAddr, u32 Mask, u32 TimeOutCount)
void XPlmi_UtilWrite64 (u32 HighAddr, u32 LowAddr, u32 Value)
Write to a 64-bit register.
int XPlmi_UtilPollForMask64 (u32 HighAddr, u32 LowAddr, u32 Mask, u32 TimeOutInUs)
64-bit Poll for a set of bits to be set (represented by Mask) or until we TimeOut
void XPlmi_UtilRMW64 (u32 HighAddr, u32 LowAddr, u32 Mask, u32 Value)
Read-modify-write a 64-bit address register.
void XPlmi_UtilWait (u32 TimeOutCount)
Wait for a period represented by TimeOut FIXME: Make it more meaningful.
void XPlmi_PrintArray (u32 DebugType, const u64 BufAddr, u32 Len, const char *Str)
This function is used to print the entire array in bytes as specified by the debug type.
char * XPlmi_Strcpy (char *DestPtr, const char *SrcPtr)
char * XPlmi_Strcat (char *Str1Ptr, const char *Str2Ptr)
s32 XPlmi_Strcmp (const char *Str1Ptr, const char *Str2Ptr)
This function is used to compare two strings.
void * XPlmi_MemCpy (void *DestPtr, const void *SrcPtr, u32 Len)
s32 XPlmi_MemCmp (const void *Buf1Ptr, const void *Buf2Ptr, u32 Len)
This function compares the data and returns the status.
Function Documentation
s32 XPlmi_MemCmp (const void * Buf1Ptr, const void * Buf2Ptr, u32 Len)
This function compares the data and returns the status.
Parameters
Buf1Ptr Pointer to the data to be compared
Buf2Ptr Pointer to the data to be compared
Len Length of the data in bytes.
Returns
None
void* XPlmi_MemCpy (void * DestPtr, const void * SrcPtr, u32 Len)
Parameters
None
Returns
None
void XPlmi_PrintArray (u32 DebugType, const u64 BufAddr, u32 Len, const char * Str)
This function is used to print the entire array in bytes as specified by the debug type.
Parameters
DebugType printing of the array will happen as defined by the debug type
Buf pointer to the buffer to be printed
Len length of the bytes to be printed
Str pointer to the data that is printed along the data
Returns
None
Note
Referenced by XPlmi_StartDma().
char* XPlmi_Strcat (char * Str1Ptr, const char * Str2Ptr)
Parameters
None
Returns
None
s32 XPlmi_Strcmp (const char * Str1Ptr, const char * Str2Ptr)
This function is used to compare two strings.
Parameters
Str1Ptr First string to be compared
Str2Ptr Second string to be compared
Returns
0 if both strings are same, -1/1 if first non matching character has lower/greater value in Str1Ptr
char* XPlmi_Strcpy (char * DestPtr, const char * SrcPtr)
Parameters
None
Returns
None
int XPlmi_UtilPoll (u32 RegAddr, u32 Mask, u32 ExpectedValue, u32 TimeOutInUs)
Parameters
Addr 32 bit address
Mask is the bit field to be updated
Value is value to be updated
TimeOutCount is delay time in us
Returns
None
if timeout value is zero, max time out value is taken
Read the Register value
Loop while the MAsk is not set or we timeout
Latch up the Register value again
Decrement the TimeOut Count
Referenced by XPlmi_CfiRead().
int XPlmi_UtilPoll64 (u64 Addr, u32 Mask, u32 ExpectedValue, u32 TimeOutInUs)
Poll for a set of bits to be cleared (represented by Mask) or until we TimeOut.
Parameters
RegAddr is the Address of the Register to be polled
Mask is the bit mask to poll for in the register value
TimeOutCount is the value to count down before return failure
Addr 64 bit address
Mask is the bit field to be polled
Expected Value is value to be polled
TimeOutCount is delay time in us
Returns
None
if timeout value is zero, max time out value is taken
Read the Register value
Loop while the Mask is not set or we timeout
Latch up the value again
Decrement the TimeOut Count
int XPlmi_UtilPollForMask (u32 RegAddr, u32 Mask, u32 TimeOutCount)
Poll for a set of bits to be set (represented by Mask) or until we TimeOut.
Parameters
RegAddr is the Address of the Register to be polled
Mask is the bit mask to poll for in the register value
TimeOutCount is the value to count down before return failure
Read the Register value
Loop while the MAsk is not set or we timeout
Latch up the Register value again
Decrement the TimeOut Count
int XPlmi_UtilPollForMask64 (u32 HighAddr, u32 LowAddr, u32 Mask, u32 TimeOutInUs)
64-bit Poll for a set of bits to be set (represented by Mask) or until we TimeOut
Parameters
HighAddr is the Upper 32-bits of the Register address to be polled
LowAddr is the Lower 32-bit of the Register address to be polled
Mask is the bit mask to poll for in the register value
TimeOutCount is the value to count down before return failure
HighAddr is higher 32-bits of 64-bit address
LowAddr is lower 32-bits of 64-bit address
Mask is the bit field to be updated
Value is value to be updated
TimeOutCount is delay time in ms
Returns
None
Read the Register value
Loop while the Mask is not set or we timeout
Latch up the value again
Decrement the TimeOut Count
int XPlmi_UtilPollForZero (u32 RegAddr, u32 Mask, u32 TimeOutCount)
Loop until all bits defined by mask are cleared or we time out
Latch up the reg value again
Decrement the timeout count
void XPlmi_UtilRMW (u32 RegAddr, u32 Mask, u32 Value)
Read Modify Write a register.
Referenced by XPlmi_CfiRead(), XPlmi_GicIntrDisable(), XPlmi_GicIntrEnable(), XPlmi_SSSCfgDmaDma(), XPlmi_SSSCfgDmaPzm(), XPlmi_SSSCfgDmaSbi(), and XPlmi_SSSCfgSbiDma().
void XPlmi_UtilRMW64 (u32 HighAddr, u32 LowAddr, u32 Mask, u32 Value)
Read-modify-write a 64-bit address register.
Parameters
HighAddr is the Upper 32-bits of the Register address to be polled
LowAddr is the Lower 32-bit of the Register address to be polled
Mask is the bit mask to poll for in the register value
Value is value to be updated
HighAddr is higher 32-bits of 64-bit address
LowAaddr is lower 32-bits of 64-bit address
Mask is the bit field to be updated
Value is value to be updated
Returns
None
int XPlmi_UtilSafetyWrite (u32 RegAddr, u32 Mask, u32 Value)
Writing a value is set of bits to be set (represented by Mask) and reading back the wriiten value to compare that write is sucessfully done.
Parameters
RegAddr is the Address of the Register to be written
Mask is the bit mask to poll for in the register value
Value is the value to be written to the register
void XPlmi_UtilWait (u32 TimeOutCount)
Wait for a period represented by TimeOut FIXME: Make it more meaningful.
Clock Cycles or MilliSeconds
Parameters
Timeout is the value to count before we return this function
void XPlmi_UtilWrite64 (u32 HighAddr, u32 LowAddr, u32 Value)
Write to a 64-bit register.
Parameters
HighAddr is the Upper 32-bits of the Register address to be written
LowAddr is the Lower 32-bit of the Register address to be written
Value is value to be updated
HighAddr is higher 32-bits of 64-bit address
LowAddr is lower 32-bits of 64-bit address
Value is value to be updated
Returns
None