xilplmi_v1_0: xplmi_err.h File Reference
xplmi_err.h File Reference
Overview
This is the file which contains .
MODIFICATION HISTORY:
Ver   Who  Date        Changes
----- ---- -------- -------------------------------------------------------
1.00  kc   05/23/2019 Initial release
Note
Functions
void XPlmi_EmInit (void)
This function initializes the error module.
void XPlmi_PsEmInit (void)
This function initializes the PSM error actions.
int XPlmi_EmSetAction (u32 ErrorId, u8 ActionId, XPlmi_ErrorHandler_t ErrorHandler)
This function sets the Action specified for a given Error ID.
void XPlmi_ErrModuleInit (void)
This function registers the PLM error commands to the PLMI.
Function Documentation
void XPlmi_EmInit (void)
This function initializes the error module.
Disables all the error actions and registers default action
Parameters
None
Returns
None
References PMC_GLOBAL_PMC_ERR1_STATUS, PMC_GLOBAL_PMC_ERR2_STATUS, PMC_GLOBAL_PMC_ERR_OUT1_DIS, PMC_GLOBAL_PMC_IRQ1_DIS, PMC_GLOBAL_PMC_POR1_DIS, PMC_GLOBAL_PMC_SRST1_DIS, XPlmi_EmSetAction(), and XPlmi_ErrModuleInit().
int XPlmi_EmSetAction (u32 ErrorId, u8 ActionId, XPlmi_ErrorHandler_t ErrorHandler)
This function sets the Action specified for a given Error ID.
Parameters
ErrorId is the error identifier
ActionId is the action that need to be set for ErrorID. Action can be SRST/POR/ERR OUT/INT
ErrorHandler If INT is defined as response, handler should be defined.
Returns
Success / failure
References XPlmi_EmDisable().
Referenced by XPlmi_EmInit(), and XPlmi_PsEmInit().
void XPlmi_ErrModuleInit (void)
This function registers the PLM error commands to the PLMI.
Parameters
none
Returns
none
Referenced by XPlmi_EmInit().
void XPlmi_PsEmInit (void)
This function initializes the PSM error actions.
Disables all the PSM error actions and registers default action
Parameters
None
Returns
None
References PMC_GLOBAL_PMC_ERR1_STATUS, PMC_GLOBAL_PMC_ERR2_STATUS, and XPlmi_EmSetAction().